[tool.ruff]
exclude = [
          ".git",
          "venv",
          "__pycache__",
          "build",
          "dist",
]
ignore = []
line-length = 119
select = [
         "E",
         "F",
         "W",
]

[tool.coverage.run]
omit = [
    ".git",
    "venv",
    "__pycache__",
    "build",
    "dist",
]
