name: Python Test

on: [push]

jobs:
  test:

    strategy:
      matrix:
        os: ["ubuntu-22.04", "ubuntu-20.04"]
        version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        exclude:
          - os: "ubuntu-22.04"
            version: "3.6"
          - os: "ubuntu-20.04"
            version: "3.7"
          - os: "ubuntu-20.04"
            version: "3.8"
          - os: "ubuntu-20.04"
            version: "3.9"
          - os: "ubuntu-20.04"
            version: "3.10"
          - os: "ubuntu-20.04"
            version: "3.11"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install ${{ matrix.version }}
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage

      - name: Flake ${{ matrix.version }}
        run: |
          flake8

      - name: Test ${{ matrix.version }}
        run: |
          coverage run check_rbl.py -w99 -c99 -a 8.8.8.8
          coverage report
